server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

