server:
  port: 9004
spring:
  application:
    name: product-service
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          # Nombre de tu circuit breaker
          externalServiceCategory:
            # Configuración del circuit breaker
            slidingWindowSize: 5
            minimumNumberOfCalls: 4
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 5s
            automaticTransitionFromOpenToHalfOpenEnabled: true
            failureRateThreshold: 5

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
