server:
  port: 9180

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rverat/spring-config-sever.git
          clone-on-start: true